global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'prometheus-es-adapter'
    static_configs:
      - targets: ['prometheus-es-adapter:9000']

remote_write:
  - url: http://prometheus-es-adapter:8000/write
remote_read:
  - url: http://prometheus-es-adapter:8000/read
    